logging:
  level:
    com:
      severett:
        transactionbank: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tbdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
